### ISSUE TITLE
proposal: add TEXTBLOCKS_CACHE_TIME setting

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#10]
one could set the cache time to a much higher value.

**Comment by benzkji** [comment]
aaahh. cache clearing is already done ;-)

**Comment by fabiangermann** [comment]
Added a setting: https://github.com/fabiangermann/django-textblocks/commit/1850e4a669f6a3b4ea605decb80e9383e7cf0f3a
