### ISSUE TITLE
make it available in python code

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#11]
`email_subject = textblock('Your request via website')`

use django.utils.get_language when no request is available, also in normal tag use.

**Comment by benzkji** [comment]
it's probably very easy. works already in #9 (with `textblock({}, 'Your request via website')` though...)

**Comment by benzkji** [comment]
#13 would resolve this.

**Comment by fabiangermann** [comment]
Should be resolved then :)
