### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#16]
catch those regressions when adding python X or django 2.8 support.

proposal: use `travis` and/or `tox`. and basic `./manage.py test`

**Comment by benzkji** [comment]
I could do this, if you agree?

**Comment by fabiangermann** [comment]
Oh sure. Some tests would be great!

**Comment by fabiangermann** [comment]
Tests and travis config provided by @matthiask are merged and a new release uploaded. Thx!
