### ISSUE TITLE
more configurable ckeditor

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#18]
for example, allow to have the same toolbar as everywhere else in the installation.

**Comment by benzkji** [comment]
proposal: add new settings `TEXTBLOCKS_CKEDITOR_CONF`. If set, use it, if not, use a default ckeditor. This implies one uses django-ckeditor, for example (and it's RichTextWidget). We could fallback to the current solution if django-ckeditor is not installed (and use the setting to locate the ckeditor js file).

**Comment by fabiangermann** [comment]
Added a setting: https://github.com/fabiangermann/django-textblocks/commit/9b8ea1bfb90057a42a3c5f70a633fbff5e3c95f6
