### ISSUE TITLE
mark_safe for type='text/html'?

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#19]
Dont know if I am doing something wrong, but shouldnt the value for 

    {% textblock 'whatever' type='text/html' %}

be returned from the tag as `mark_safe` text? strange thing is, running it on django 1.8 didnt escape anything, but updating to 1.9 "ruins" everything in my current project?

**Comment by benzkji** [comment]
gladly, django 1.9 has the `as`...

    {% textblock 'whatever' type='text/html' as whatever %}
    {{ whatever|safe }}

solves it for now... but is a bit cumbersome.

**Comment by fabiangermann** [comment]
Is this still a problem the current version on github? This should have been fixed with commit 3ecd8fb9b1ab94037f42f0e3e02cf3e33673fbe8. I also just uploaded a new release to pypi containing this fix.

**Comment by benzkji** [comment]
aah. nice. no, I was using 0.3! thx!
