### ISSUE TITLE
a way to find deprecated/no more used keys

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#21]
when projects evolve, and refactorings happen, some keys might no longer be needed. having an indicator for more safe deletion of textblocks would be nice. one indicator could be the last time accessed a key was used/accessed.

**Comment by fabiangermann** [comment]
Added timestamp fields: https://github.com/fabiangermann/django-textblocks/commit/1054c882cea3bcc65f691fe9c28219fe86fe2ef3
