### ISSUE TITLE
proposal: optionally render content with a template

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#25]
so one can easily override that template. mainly usefull for applying custom filters (email protection, whatever) or cleanup on html textblocks.

    TEXTBLOCKS_USE_TEMPLATE = (defaults to False)

**Comment by fabiangermann** [comment]
The tag now tries to render with a template named after the (slugified) type (textplain.html, texthtml.html) first before returning the text value.

https://github.com/fabiangermann/django-textblocks/commit/ed9474221c4cdbf07cd06f25dd7cd8c859d32cea
