### ISSUE TITLE
confusion with modeltranslation / MIGRATION_MODULES

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#3]
I tried to install django-textblocks. I have modeltranslation installed. In my main app, created a `migrations_textblocks` folder, with an `__init__.py`. 

Added to settings:

```
MIGRATION_MODULES = {
    'textblocks': 'main_app.migrations_textblocks',
}
```

When running makemigrations, all my existing apps are considered unmigrated. Is there an easy workaround, or do I have to enter all my existing apps to `MIGRATION_MODULES` (a no go, in my opinion)? Or, am I configuring `MIGRATION_MODULES` the wrong way round?

**Comment by fabiangermann** [comment]
Do you just run `makemigrations` or do you also provide the `textblocks` app name? You should be able to use migrations for just a single app as follows:

`./manage.py makemigrations textblocks`
`./manage.py migrate textblocks`

**Comment by benzkji** [comment]
thx!

you mean, add MIGRATION_MODULES setting as mentioned, run `./manage.py makemigrations textblocks` (and migrate), and then change settings again? yes, this would probably work. but is somehow strange, and error prone IMHO? Also it does not integrate with for example fabric or other deployment tools, as far as I understand (I mean, I would have to manually migrate on the deployed site, right?).

or am I still getting it wrong?!

**Comment by fabiangermann** [comment]
I haven't tested it but I think you can just execute `/.manage.py makemigrations textblocks` once to create the migration files. After that call `/.manage.py migrate` without providing the app name (or do this in your deployment script). After all django can only migrate apps that have migrations available. So this should work just fine.

**Comment by benzkji** [comment]
tried again. works. like a charm. dont know what was wrong last time. ;-=)
