### ISSUE TITLE
allow ckeditor config to contain lazy objects

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#37]
as for example [here,](https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor/widgets.py) with a `LazyEncoder` . Otherwise, translated or other lazy objects (`reverse_lazy` in my case) are not possible in the config (serialization error).

**Comment by benzkji** [comment]
@matthiask any objections on this? would help me quite a lot.

**Comment by matthiask** [comment]
@benzkji It's definitely not up to me to decide :)

The LazyEncoder seems simple to add. For now you can always use your own `ModelAdmin` class with your own customizations for the text field widget?

**Comment by benzkji** [comment]
no offense @fabiangermann  ;-)

sure, `ModelAdmin` and custom widget is quite easy, but this involves a lot more code, for every project.

try to stick together a PR.

**Comment by fabiangermann** [comment]
@benzkji none taken, and thank you, a PR would be helpful :)

**Comment by benzkji** [comment]
see PR
