### ISSUE TITLE
proposal: define a setting to show the key, when no content is defined

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#4]
via a setting (or seperate tag/tag parameter, may be even better/more flexible?), one could show the `key` of a textblock, if no content is defined. kind of like i18n works? I'm "misusing" textblocks as kind of i18n replacement, as it works much more straightforward, and content can be edited easier, also by clients (no make/compilemessages, configuring, etc)...thus the request.

I'm willing to implement it (seems not too complicated ;-), if you are willing to merge it?

**Comment by fabiangermann** [comment]
Absolutely! I think that's a good idea.

Personally I think that both approaches have their merit. If one would like to show the key all the time it'd be cumbersome to set the additional parameter all the time. On the other hand a parameter would definitely make it more flexible, if you want to show it only for some textblocks.

Maybe a parameter with a default value of False and a setting to permanently activate it would be the best way to go.

If you've time to implement it, I'll be happy to merge it. Just make sure the parameter has a default value of False and does not need to be set, and that the setting does not have to be set either (for backwards compatibility of course).
